<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="1" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-04-20T09:06:14Z" name="Default suite" finished-at="2023-04-20T09:06:14Z" duration-ms="20">
    <groups>
    </groups>
    <test started-at="2023-04-20T09:06:14Z" name="Default test" finished-at="2023-04-20T09:06:14Z" duration-ms="20">
      <class name="exception.Topic_03_Try_Catch_Finally">
        <test-method signature="TC_01_catch1()[pri:0, instance:exception.Topic_03_Try_Catch_Finally@2b546384]" started-at="2023-04-20T09:06:14Z" name="TC_01_catch1" finished-at="2023-04-20T09:06:14Z" duration-ms="6" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_01_catch1 -->
      </class> <!-- exception.Topic_03_Try_Catch_Finally -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
